# GitBook Configuration

site_name: VoiceRecruit Documentation
site_description: Documentation complète pour l'application VoiceRecruit
site_author: VoiceRecruit Team

nav:
  - Accueil: README.md
  - Architecture technique: architecture.md
  - Guide d'utilisation: user-guide.md
  - API et intégrations: api.md
  - Déploiement: deployment.md
  - FAQ: faq.md

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  language: fr
  logo: assets/logo.png
  favicon: assets/favicon.ico

extra:
  alternate:
    - name: Français
      link: /
      lang: fr
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/voicerecruit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/voicerecruit
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/voicerecruit

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: date
  - mkdocs-material
